locals {
  tags = merge(var.tags, {
    // Due to s3 bucket name cannot be duplicated, add previous bucket name to the tag
    PrevBucketName = var.bucket_name
  })
}
// to meet the requirement of the s3 bucket name, we need to add a random string to the bucket name with lower case
resource "random_string" "bucket_name" {
  length  = 8
  special = false
  lower   = true
  upper   = false
}

resource "aws_s3_bucket" "this" {
  bucket              = "${var.bucket_name}-${random_string.bucket_name.result}"
  force_destroy       = var.force_destroy
  object_lock_enabled = var.object_lock_enabled
  tags                = var.tags
}


# # __generated__ by Terraform from "s3-simple-vpc-flow-logs"
# resource "aws_s3_bucket_policy" "s3-bucket-policy-for-vpc-flow-logs" {
#   bucket = aws_s3_bucket.s3-bucket-for-vpc-flow-logs.bucket
#   policy = var.bucket_policy

# }

// This sort of Bucket policy for VPC Flow Logs will be generated by AWS when you create a VPC Flow Log
# {
#     "Version": "2012-10-17",
#     "Id": "AWSLogDeliveryWrite20150319",
#     "Statement": [
#         {
#             "Sid": "AWSLogDeliveryWrite",
#             "Effect": "Allow",
#             "Principal": {
#                 "Service": "delivery.logs.amazonaws.com"
#             },
#             "Action": "s3:PutObject",
#             "Resource": "arn:aws:s3:::aws-vpc-flow-logs-share-20240129-proserve-korea/AWSLogs/347263326312/*",
#             "Condition": {
#                 "StringEquals": {
#                     "aws:SourceAccount": "347263326312",
#                     "s3:x-amz-acl": "bucket-owner-full-control"
#                 },
#                 "ArnLike": {
#                     "aws:SourceArn": "arn:aws:logs:ap-northeast-2:347263326312:*"
#                 }
#             }
#         },
#         {
#             "Sid": "AWSLogDeliveryAclCheck",
#             "Effect": "Allow",
#             "Principal": {
#                 "Service": "delivery.logs.amazonaws.com"
#             },
#             "Action": "s3:GetBucketAcl",
#             "Resource": "arn:aws:s3:::aws-vpc-flow-logs-share-20240129-proserve-korea",
#             "Condition": {
#                 "StringEquals": {
#                     "aws:SourceAccount": "347263326312"
#                 },
#                 "ArnLike": {
#                     "aws:SourceArn": "arn:aws:logs:ap-northeast-2:347263326312:*"
#                 }
#             }
#         }
#     ]
# }
